# Cloud Deployment Configuration
# Deploy to any cloud provider (AWS, Google Cloud, Azure, Heroku, etc.)

version: '3.8'

services:
  fhir-web:
    build: .
    ports:
      - "80:5000"
    environment:
      - FLASK_ENV=production
      - HOST=0.0.0.0
      - PORT=5000
    volumes:
      - ./uploads:/app/uploads
      - ./fhir_bundles:/app/fhir_bundles
    restart: unless-stopped
